Remove CAPI tracker by Pinterest request.
woocommerce/pinterest-for-woocommerce pull request #1026
Opened 2024-06-21 11:21 UTC by message-dimke

### Changes proposed in this Pull Request:

Disabling Conversion API tracker according to some temporary legal aspects from Pinterest.

### How to test.

1. Install Pinterest extension.
2. Following the Connect Wizard, set up conversion tracking.

<img width="577" alt="Pinterest" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/b2f1e5f9-91a7-4e7a-a5ac-0f2c1325975d">

3. Setting up conversion tracking will send the extension corresponding boolean flags to indicate Pinterest Tag tracking and Conversions API tracking must be enabled.
4. Check `pinterest_for_woocommerce` option inside `wp_options` database table.
5. The option must include `s:22:"track_conversions_capi";b:0;` serialized data.
6. The above will indicate the despite Pinterest is sending us Conversions API is `ON`, we force it `OFF` into options.
e.g. `s:17:"track_conversions";b:1;s:22:"track_conversions_capi";b:0;`: Pinterest Tag on `ON`, but Conversions API is `OFF`.

### Changelog entry

> Update - Disabling CAPI tracker.

2024-06-21 11:31 UTC, budzanowski requested changes
We should do it via separate setting for CAPI. We should make the capi tracker option false. No UI for it would mean that we don't have to do anything else for now.

During the testing you just switch the CAPI tracker option to true and you can run the tests. We don't want to delete them because we will have to reintroduce them back very soon.

2024-06-23 11:39 UTC, message-dimke commented
> We should do it via a separate setting for CAPI. We should make the capi tracker option false. No UI for it would mean that we don't have to do anything else for now.

When connecting to Pinterest, Pinterest replies back with a set of features and their corresponding statuses. The set looks like this:
```
tags => bool
CAPI => bool
catalog => bool
```
 
The three flags above indicate what was chosen during the onboarding wizard (a Pinterest-hosted wizard). For example, choosing to sync catalog will send the `catalog` flag set to `true`.

The problem is tracking. Pinterest has a single wizard screen for tracking and a single yes/no button that turns ON/OFF both `tags` and `CAPI` flags synchronously. So, without forcing CAPI tracking to `false`, we can not disable that type of tracking.

Introducing the new `track_conversions_capi` setting will default to `false` for all the existing plugin users, but for the new ones, it will be set to the value selected while onboarding. Taking this into account, I will force the setting to false when the new user is connecting, no matter what the wizard returns to us.

Does it make sense?

2024-06-24 07:14 UTC, budzanowski commented
>  I will force the setting to false when the new user is connecting, no matter what the wizard returns to us.

For now this is good enough. We can change it later when they will have separate consents.

2024-06-24 08:37 UTC, budzanowski commented
Looks good. Do we need to add plugin update procedure that sets CAPI tracking to false explicitly? Or not set will default to false?

2024-06-24 08:47 UTC, message-dimke commented
If the setting is empty or there is no such setting, it will resolve to `false`.

https://github.com/woocommerce/pinterest-for-woocommerce/blob/c85534a9f5d6f4f76fe673de2ffef84ba98999ab/class-pinterest-for-woocommerce.php#L557-L562

If I read it correct =)
Anyway, I have unit tests that should test this as well.

2024-06-25 07:26 UTC, budzanowski approved these changes
OK lets do it. Please remember that this should be a GitHub only release.

2024-06-25 11:36 UTC, merged