Feaure/merchant health check
woocommerce/pinterest-for-woocommerce pull request #227
Opened 2021-10-18 20:19 UTC by ksere

Closes #160 
Closes #141

### Changes proposed in this pull request

#### Screenshots

![Screenshot 2021-10-18 231107](https://user-images.githubusercontent.com/4016167/137800688-1e9e3f87-ae0b-4bbe-947b-8c0e4bd25013.png)

![Screenshot 2021-10-18 231355](https://user-images.githubusercontent.com/4016167/137800684-d675c68a-04aa-4de1-9f3d-dc45b72ac27f.png)

![Screenshot 2021-10-18 231627](https://user-images.githubusercontent.com/4016167/137800690-6158405d-76a4-4f5d-b6db-f76f1604a41a.png)

![Screenshot 2021-10-18 231512](https://user-images.githubusercontent.com/4016167/137800691-fe6f680e-47fb-447a-b484-fa531e6cf12b.png)

### Detailed test instructions

1. 
2. 
3. 

### Changelog note

> Fix|New|Dev: Add suggested changelog note here

2021-10-19 15:48 UTC, msaggiorato approved these changes
Looks good at first sight. Nice to see the rearranging of code and separating thigns further for better organization.

Lets run through QA.

2021-10-20 05:35 UTC, findingsimple commented
@eason9487 (as porter) or @tomalec would you mind taking a glance at the JS side of things in this one please? @ecgan [indicated it likely to be mostly backend related ](https://github.com/woocommerce/pinterest-for-woocommerce/issues/160#issuecomment-929294564) so happy to hear thoughts on approach here as well.

Keen to wrap it up, so can be pragmatic about the review and we can do follow ups.

2021-10-20 09:31 UTC, eason9487 commented on assets/source/setup-guide/app/components/HealthCheck/index.js
> +	const checkHealth = useCallback( async () => {
The `checkHealth` value in this useEffect deps array is always `undefined`. Even though it could still result in expected behavior in runtime - call `checkHealth()` only once after component mounted, it hides a potential problem here.

I'd suggest moving this useEffect block to the below of `checkHealth` declaration, and wrapping the returned function of [`useCreateNotice`](https://github.com/woocommerce/pinterest-for-woocommerce/blob/53e667494c5f2aed0904af3ec82b56d14fb2a04c/assets/source/setup-guide/app/helpers/effects.js#L24-L28) by `useCallback` to prevent its reference from changing when every rendering. Such as:

```js
export const useCreateNotice = () => {
	const { createNotice } = useDispatch( 'core/notices' );

	return useCallback(
		( type, message ) => message && createNotice( type, message ),
		[ createNotice ]
	);
};
```

But considering there're many `useCreateNotice` usages in other places, it might cause more side effects. We could create a follow-up issue to fix it later if it has not much time to address it in this PR.

2021-10-20 09:31 UTC, eason9487 commented on assets/source/setup-guide/app/components/HealthCheck/index.js
> +	if ( healthStatus.status === 'error' ) {
If the intention here is to handle unknown errors by the fallback message "Could not fetch account status" below, it would need to adjust this condition. Otherwise, it would show a blank error notice block.

![image](https://user-images.githubusercontent.com/17420811/138053267-af2d0cf0-70e3-4ba7-829f-66f7146a13c1.png)


```suggestion
	if ( notice.status === 'error' ) {
```

2021-10-20 11:41 UTC, eason9487 commented
> @ecgan [indicated it likely to be mostly backend related ](https://github.com/woocommerce/pinterest-for-woocommerce/issues/160#issuecomment-929294564) so happy to hear thoughts on approach here as well.

I've read #160 over several times but am not really sure I understand the context correctly. By this PR, it shows the declined merchant a clearer error message and reasons.

![image](https://user-images.githubusercontent.com/17420811/138070392-0d7d71e1-3e9d-4294-83f1-5d1f0a14f70b.png)

---

I suspect the root cause of #160 might be that in a certain version of codebase, after finishing the onboarding and being redirected to
1. the Catalog tab directly.
2. the Settings tab directly with triggering the creation of Pinterest product pin merchant, and then goes to the Catalog tab as quickly as possible.
3. the Settings tab directly without triggering the creation of merchant, and then going to the Catalog tab.

If one of the assumptions happened, then there's a chance that the timing of merchant creating is later than the querying of `pinterest/v1/feed_state` API, which further causes that error to occur.

By the current `develop`, [the merchant is created](https://github.com/woocommerce/pinterest-for-woocommerce/blob/4a1f1f88b9876939a70f8322398f2eadfd16d728/src/ProductSync.php#L615-L621
) only when calling to `ProductSync::get_merchant`. But the [FeedState.php](https://github.com/woocommerce/pinterest-for-woocommerce/blob/4a1f1f88b9876939a70f8322398f2eadfd16d728/src/API/FeedState.php#L252) (`pinterest/v1/feed_state` API) calls to `Base::get_merchant`, which calls to Pinterest API for querying merchant data without the fallback handling as above.

So, it might have a chance/timing that the merchant is not yet created when querying `pinterest/v1/feed_state` API.

---

After this PR, the `<HealthCheck>` UI is displayed on each tab, and its corresponding API calls `Merchants::get_merchant` (formerly `ProductSync::get_merchant`), which the one would try to create the merchant account. And with the Settings tab is the first page after completing onboarding, so now the error probably only occurs by switching to the Catalog tab very quickly.

---

If now we only want to make the error message looks nicer, as Gan mentioned, the frontend is not currently suitable for handling that error and there is no error code to identify it. I'd suggest adding some handling, such as `650 === $th->get_pinterest_code()`, at the FeedState.php with some polished error message:

https://github.com/woocommerce/pinterest-for-woocommerce/blob/53e667494c5f2aed0904af3ec82b56d14fb2a04c/src/API/FeedState.php#L294-L297

Otherwise, basically the merchant not found error handling is still pretty much the same.

![image](https://user-images.githubusercontent.com/17420811/138085539-fab659d3-189b-4503-a60b-a009c1620c9e.png)

2021-10-20 13:22 UTC, ksere commented
Hi @eason9487, thanks for the feedback!

> By the current `develop`, [the merchant is created](https://github.com/woocommerce/pinterest-for-woocommerce/blob/4a1f1f88b9876939a70f8322398f2eadfd16d728/src/ProductSync.php#L615-L621) only when calling to `ProductSync::get_merchant`. But the [FeedState.php](https://github.com/woocommerce/pinterest-for-woocommerce/blob/4a1f1f88b9876939a70f8322398f2eadfd16d728/src/API/FeedState.php#L252) (`pinterest/v1/feed_state` API) calls to `Base::get_merchant`, which calls to Pinterest API for querying merchant data without the fallback handling as above.
> 
> So, it might have a chance/timing that the merchant is not yet created when querying `pinterest/v1/feed_state` API.

The `Base::get_merchant` in FeedState.php (pinterest/v1/feed_state) is called after [getting the stored Merchant ID](https://github.com/woocommerce/pinterest-for-woocommerce/blob/4a1f1f88b9876939a70f8322398f2eadfd16d728/src/API/FeedState.php#L248). If we do have a stored Merchant ID, then the merchant is already created and `Base::get_merchant` should return the merchant object and not an error.

2021-10-20 20:47 UTC, JPry requested changes

2021-10-20 20:47 UTC, JPry commented on src/API/Base.php
> +	 * @throws \PinterestApiException PHP exception.
This should match the import at the top of the file.

```suggestion
	 * @throws ApiException PHP exception.
```

2021-10-20 20:47 UTC, JPry commented on src/API/Base.php
> +				),
```suggestion
				array(
					'message'       => $message,
					'response_body' => $body,
				),
```

2021-10-20 20:47 UTC, JPry commented on src/API/DomainVerification.php
> +					'pinterest_code' => is_callable( array( $th, 'get_pinterest_code' ) ) ? $th->get_pinterest_code() : 0,
```suggestion
					'pinterest_code' => method_exists( $th, 'get_pinterest_code' ) ? $th->get_pinterest_code() : 0,
```

2021-10-20 20:47 UTC, JPry commented on src/API/HealthCheck.php
> +				throw new \Exception( esc_html__( 'Could not get approval status from Pinterest.', 'pinterest-for-woocommerce' ), 200 );
I see that this is being done elsewhere, but given that this is an API response, I don't believe `esc_html__()` is the correct function to use here. Instead, the normal `__()` function should be used instead.

```suggestion
				throw new \Exception( __( 'Could not get approval status from Pinterest.', 'pinterest-for-woocommerce' ), 200 );
```

2021-10-20 20:47 UTC, JPry commented on src/API/HealthCheck.php
> +			$error_message = sprintf( esc_html__( 'Could not fetch account status. [%s]', 'pinterest-for-woocommerce' ), $th->getMessage() );
```suggestion
			$error_message = sprintf( __( 'Could not fetch account status. [%s]', 'pinterest-for-woocommerce' ), $th->getMessage() );
```

2021-10-20 20:47 UTC, JPry commented on src/API/HealthCheck.php
> +				'status' => esc_html( $merchant['data']->product_pin_approval_status ),
```suggestion
				'status' => $merchant['data']->product_pin_approval_status,
```

2021-10-20 20:47 UTC, JPry commented on src/Merchants.php
> +			throw new \Exception( esc_html__( 'Response error when trying create a merchant or get the existing one.', 'pinterest-for-woocommerce' ), 400 );
```suggestion
			throw new \Exception( __( 'Response error when trying create a merchant or get the existing one.', 'pinterest-for-woocommerce' ), 400 );
```

2021-10-20 20:47 UTC, JPry commented on src/Merchants.php
> +			throw new \Exception( esc_html__( 'Response error when trying to get advertisers.', 'pinterest-for-woocommerce' ), 400 );
```suggestion
			throw new \Exception( __( 'Response error when trying to get advertisers.', 'pinterest-for-woocommerce' ), 400 );
```

2021-10-20 20:47 UTC, JPry commented on src/Merchants.php
> +		return ! empty( $advertiser->merchant_id ) ? $advertiser->merchant_id : null;
Instead of returning `null`, it would be better to throw an `Exception` and allow the calling function to catch that exception. Then this function only has one type of return value.

2021-10-21 07:52 UTC, eason9487 commented on assets/source/setup-guide/app/components/HealthCheck/index.js
> +	const checkHealth = useCallback( async () => {
> I'd suggest moving this useEffect block to the below of `checkHealth` declaration, and wrapping the returned function of [`useCreateNotice`](https://github.com/woocommerce/pinterest-for-woocommerce/blob/53e667494c5f2aed0904af3ec82b56d14fb2a04c/assets/source/setup-guide/app/helpers/effects.js#L24-L28) by `useCallback` to prevent its reference from changing when every rendering. Such as:
> 
> ```js
> export const useCreateNotice = () => {
> 	const { createNotice } = useDispatch( 'core/notices' );
> 
> 	return useCallback(
> 		( type, message ) => message && createNotice( type, message ),
> 		[ createNotice ]
> 	);
> };
> ```

Hi @ksere, the `useCreateNotice` function needs the above adjustment along with https://github.com/woocommerce/pinterest-for-woocommerce/pull/227/commits/c9b2e98c198e76c07086f084da3fa35a86f37b3e. Otherwise, it will keep querying the `pinterest/v1/health` API.

![Kapture 2021-10-21 at 15 14 55](https://user-images.githubusercontent.com/17420811/138233829-47b082f7-b2ee-4cfb-95de-6c1cf76da16d.gif)

2021-10-21 10:09 UTC, eason9487 commented
Hi @ksere, I found more clues about #160 😄 

## Previous thought

> The `Base::get_merchant` in FeedState.php (pinterest/v1/feed_state) is called after [getting the stored Merchant ID](https://github.com/woocommerce/pinterest-for-woocommerce/blob/4a1f1f88b9876939a70f8322398f2eadfd16d728/src/API/FeedState.php#L248). If we do have a stored Merchant ID, then the merchant is already created and `Base::get_merchant` should return the merchant object and not an error.

Yes. But I thought if their database/cache has distributed read/write architecture, in some cases the data just written may not be synced to the database/cache instances used for reading, resulting in inconsistent data for a short period of time. And from the #160 log, I saw there is only a 2 second gap between the requests of account creation and read. Therefore, had that speculation yesterday.

```
2021-08-16T13:05:55+00:00 DEBUG POST Request: https://api.pinterest.com/v3/commerce/product_pin_merchants/
2021-08-16T13:05:57+00:00 DEBUG GET Request: https://api.pinterest.com/v3/commerce/product_pin_merchants/{{merch_id}}/
```

## Root cause

However, after deeper investigations, I think I found the root cause.

At approximately version `1.0.0-beta.1`, the implementation of [`ProductSync::register_feed()`](https://github.com/woocommerce/pinterest-for-woocommerce/blob/1.0.0-beta.1/src/ProductSync.php#L464-L499) had some problem as follows:

1. If enter this condition, it would assign the response of `API\Base::add_merchant_feed` to `$merchant`, but that response data should be treated as **feed** rather than **merchant**, where the `$merchant['data']->id` belongs to feed after the variable assignment.
    https://github.com/woocommerce/pinterest-for-woocommerce/blob/21a15c3514b7d7427ba5b1d13605c3b1cbb424a0/src/ProductSync.php#L473-L475
1. Under the same function, the `$merchant['data']->id` will be stored, but at this time the `id` is the feed's id. And then it causes the wrong id to be used when requesting merchant data later.
    https://github.com/woocommerce/pinterest-for-woocommerce/blob/21a15c3514b7d7427ba5b1d13605c3b1cbb424a0/src/ProductSync.php#L496
1. I reproduced #160 with version `1.0.0-beta.1`

    https://user-images.githubusercontent.com/17420811/138254644-87c64bed-9c1d-481c-8bca-f0cb3d4852be.mp4
1. The debug log is basically the same when reproducing it. We can find that the merchant ID is changed from **1447262861339** to **1569352766736** after creating feed:
    ```
    2021-10-21T09:15:23+00:00 DEBUG POST Request: https://api.pinterest.com/v3/commerce/product_pin_merchants/
    2021-10-21T09:15:24+00:00 DEBUG POST Request: https://api.pinterest.com/v3/commerce/product_pin_merchants/1447262861339/feed/
    2021-10-21T09:15:34+00:00 DEBUG GET Request: https://api.pinterest.com/v3/commerce/product_pin_merchants/1569352766736/
    ```

## Current situation

Fortunately 🎉 , this bug has been fixed by the https://github.com/woocommerce/pinterest-for-woocommerce/commit/8cf36bf6de5165807c8e85747121bccaf5e626a5 in PR #182. So if the error handling and its message are not the primary concern here, then I believe the bug in #160 has been solved at all.

2021-10-21 13:55 UTC, ksere commented
> Hi @ksere, I found more clues about #160 😄

Thanks again @eason9487 for the very thorough investigation! 🥇

2021-10-21 14:14 UTC, eason9487 approved these changes
The JS side looks good to me.

2021-10-23 01:00 UTC, JPry approved these changes
The change here look good 👍🏻

2021-10-24 22:16 UTC, merged