Fix/228 wrong feed registration status multiple feed profiles
woocommerce/pinterest-for-woocommerce pull request #293
Opened 2021-12-08 18:42 UTC by ksere

### Changes proposed in this Pull Request:

Closes #228 .

When a merchant has multiple feeds, we should get the feed report, in order to populate the status of the feed, using the stored feed_id. 

### Screenshots:
![image](https://user-images.githubusercontent.com/4016167/145265426-327a9c4a-38f8-4ee3-8c40-14fefa9c4d72.png)

### Detailed test instructions:

1. Create a feed profile using https://www.pinterest.com/product-catalogs/ directly and then disable it.
2. Install & finish onboarding of the plugin so that a new feed profile is registered by the plugin.
3. Verify that the status shown in the product catalog page is of the expected feed (the one created by the plugin).

### Changelog entry

> Fix - Get feed report for the stored Feed ID instead for the first feed returned by the API.
> Add - get_merchant_feed_report() method that fetches the feed_report
> Tweak - get_merchant_feed() now fetches the feed instead of the feed_report.

2021-12-09 00:29 UTC, jconroy commented
Thanks @ksere and @alexiglesias31 

I've requested a review from Ventures

2021-12-09 21:50 UTC, JPry requested changes

2021-12-09 21:50 UTC, JPry commented on src/API/Base.php
>  	 * @return mixed
This `@return` should be updated to match the structure of `$feed_profile`. That's the only possible return value, as everything else results in a thrown exception.

2021-12-09 21:50 UTC, JPry commented on src/API/FeedState.php
> +			}
This check is unnecessary, as the `get_merchant_feed()` method can only return a valid profile or throw an exception.

```suggestion
```

2022-01-19 22:25 UTC, JPry approved these changes
Sorry for the delay, this dropped off my radar to look at again. The changes look good to me 👍🏻

2022-01-19 22:41 UTC, jconroy commented
Just need to get the 🟢 on JS linting

2022-01-20 09:56 UTC, ecgan commented
> Just need to get the 🟢 on JS linting

I looked into the [failed JavaScript and CSS Linting check](https://github.com/woocommerce/pinterest-for-woocommerce/runs/4877694888?check_suite_focus=true). It fails because this PR is coming from a public fork, and therefore the `GITHUB_TOKEN` has only read permissions (see screenshot below). Other PRs within this repo (not a fork) does not have this problem, as the `GITHUB_TOKEN` in those PR has write permissions.

![image](https://user-images.githubusercontent.com/417342/150315889-ecb34e19-b34a-489b-9f07-a782ab470aca.png)

References:

- [Automatic token authentication](https://docs.github.com/en/actions/security-guides/automatic-token-authentication)
- [GitHub Actions: Control permissions for GITHUB_TOKEN](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/)

---

@ksere , heads up: there is a conflict in your PR here.

2022-01-21 11:49 UTC, budzanowski commented
This just needs merge conflicts removed.

2022-01-21 16:45 UTC, closed without merging