Fix/325 consistent price format
woocommerce/pinterest-for-woocommerce pull request #345
Opened 2022-01-31 18:24 UTC by alexiglesias31

### Changes proposed in this Pull Request:

Closes #325 .

Add the prices to the feed with the proper decimal format like 10.00USD (second format of the screenshot).
UT was updated to success with the new changes.

### Screenshots:

![149070840-9fa2244d-f306-4b30-8626-73ecca462068](https://user-images.githubusercontent.com/40774170/151850671-226e28d2-61cf-4bbf-8961-f1005592108a.png)

### Detailed test instructions:

1. Create a product with a non-decimal price (like 10USD).
2. Verify that the price in the feed is in decimal format (like 10.00USD).
3. Verify that UT are success with the new changes.

### Additional details:

### Changelog entry

>

2022-02-01 17:47 UTC, budzanowski commented
In WooCommerce the number of decimal points is configurable in the settings. Since the Feed has specific requirements the code may be forced to be indifferent to the system settings. The number of decimal points settings is available at WooCommerce > Settings > General ( bottom of the tab )
![image](https://user-images.githubusercontent.com/17271089/152020467-8d04efdd-8324-4d6e-8465-8acc73e73da8.png) 

We should confirm with Pinterest if a variable precision is acceptable. I am mentioning this because we have seen sites that are using for example USD ( so they should use 2 decimal points according to ISO-4271 ) but site owners want to use 0 numbers for precision - for example, because they sell higher-priced products and they want to just show 1000 USD as a price sitewide. If we would be forced to use 2 number precision in such cases then this, in turn, would mean that we can't really rely on the `wc_get_price_decimals` function.

2022-02-01 18:47 UTC, ksere requested changes
Great feedback, thanks Bartosz. 

I 'd say since the document is clear enough we go with the default decimal points for the given currency. We should be able to get that from [locale-info.php](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/locale-info.php).

2022-02-04 18:35 UTC, ksere requested changes

2022-02-04 18:35 UTC, ksere commented on src/ProductsXmlFeed.php
> +	private static function get_currency_decimals() {
This won't produce the desired output if for example my base country is US and my currency is JPY.
We need to get the decimals from that array based on the currency returned by `get_woocommerce_currency()`

2022-02-09 20:26 UTC, ksere approved these changes

2022-02-09 20:26 UTC, ksere commented on src/ProductsXmlFeed.php
> +		$locale_info = include WC()->plugin_path() . '/i18n/locale-info.php';
Maybe move the `include` in the conditional as well so that it doesn't load up the array when not needed.

2022-02-14 17:54 UTC, budzanowski commented
This looks great, approving. Could you please add one additional test where you use different currency - to highlight that the formatting for different decimal points works?

2022-02-14 17:55 UTC, budzanowski approved these changes

2022-02-14 22:25 UTC, alexiglesias31 commented
Done @budzanowski. Added the unit test with JPY (that has 0 decimals as default).

2022-02-15 08:51 UTC, budzanowski commented
I have updated the changelog entry in the PR description. Please make sure to have it as it is used by our release tool to automatically populate the changelog.

2022-02-15 08:52 UTC, merged