Omit zero price products
woocommerce/pinterest-for-woocommerce pull request #350
Opened 2022-02-01 20:20 UTC by alexiglesias31

### Changes proposed in this Pull Request:

Closes #265 .

Exclude $0.00 price products on feed generation.
---
**Pinterest** does not support ingesting $0.00 price products.

### Screenshots:

### Detailed test instructions:
1. Add a product with 0.00 price
2. Verify that is not included in the feed

### Additional details:
### Changelog entry

2022-02-03 20:37 UTC, ksere requested changes
Small comment on a method's return type

2022-02-03 20:37 UTC, ksere commented on src/ProductsXmlFeed.php
> +	 * @return string|null
Prefer keeping 1 single return type. 
And check for empty string where needed

2022-02-03 21:30 UTC, ksere commented on src/ProductSync.php
> +				if ( $xml_item ) {
```suggestion
				if ( '' !== $xml_item ) {
```

2022-02-03 21:34 UTC, ksere approved these changes

2022-02-15 09:44 UTC, budzanowski commented
Rebased with `develop` to fix merge conflicts.

2022-02-15 09:44 UTC, budzanowski approved these changes

2022-02-15 09:47 UTC, merged