Fix multiple registered feeds on site language change.
woocommerce/pinterest-for-woocommerce pull request #650
Opened 2022-12-05 14:21 UTC by budzanowski

### Changes proposed in this Pull Request:

When the user changes the locale a new feed configuration is created. It now reflects the new locale ( language ). We can't delete the old feed configuration ( API limitation ) but we can disable it. 

Closes #643  .

- Correctly identify the registered feed configuration as local.
- Make sure that the additional old feed configurations are disabled.

### TODO:
- [x] cache invalidation.
- [x] remove TODOs comments.
- [x] feed enable feature when feed configuration detected but not enabled.
- [x] comments.

### Screenshots:

### Detailed test instructions:

**Using develop**

( this is a copy from #643 )
1. Log into your account
2. Go to Settings -> General
3. Change Site Language
4. Wait 2 hours
5. Go to the Pinterest Ads portal and go to Ads -> Catalogs.
6. You will see more than 1 catalog record

**Switch to this branch**
Wait for some time ( < 10 minutes ) The automation should clean things up.
You should receive an email about that a data source has been deleted - Pinterest is working on making that message less scary.
If you now check the feed records in Pinterest UI there should be only one active.

### Additional details:

The code in this PR checks for all of the feed configurations and acts only on the ones that are registered as WooCommerce integrations. It also compares the URLs. This means that the cleanup procedure only works for multiple feed files that are coming from the same website. Connecting multiple ( different ) sites is still supported (whether that is good or bad is a different discussion and more a business decision )

### Changelog entry

> Fix -  Prevent multiple active feed files.

2022-12-05 14:22 UTC, budzanowski commented
This is a Draft state since there are some issues with the API access and thus this PR is not testable.

2023-02-20 12:18 UTC, message-dimke requested changes

2023-02-20 12:18 UTC, message-dimke commented on src/FeedRegistration.php
> +		}
If I have a locally registered feed option, then it will never search for a locale different feed and update it unless the `feed_registered` option is emptied.

My suggestion is let it search for a matching feed and create a new one or reactivate an old one if any.

```suggestion
		$feed_id = Feeds::match_local_feed_configuration_to_registered_feeds( $merchant_id );
```

Also there is a problem if new locale does not match any of Pinterest locales, but I think it is fixed with another PR. So for example if I set my locale to New Zealand then it does not update and just quits with an Exception (the exception has no meaningful message and just says something like Unsupported parameter). I assume this is a locale problem since I haven't found New Zealand from the list of supported locales by Pinterest and other locations like Australia, United Kingdom or US those do work well. I'll check this case when reviewing locale mapping PR once again.

2023-02-20 15:26 UTC, budzanowski commented on src/FeedRegistration.php
> +		}
> My suggestion is let it search for a matching feed and create a new one or reactivate an old one if any.

This is how it was actually done before. I think that I have tried to bee a bit too smart. Great catch.

> Also there is a problem if new locale does not match any of Pinterest locales, but I think it is fixed with another PR.
Yes this is handled by https://github.com/woocommerce/pinterest-for-woocommerce/pull/687 so we don't have to think about this here. But good point nevertheless.

2023-02-20 15:27 UTC, budzanowski commented
@message-dimke update made.

2023-02-20 16:49 UTC, message-dimke approved these changes
Good to go! Thank you, @budzanowski !

2023-02-21 08:36 UTC, merged